//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_and_Placement_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchwiseByYearView
    {
        public string bname { get; set; }
        public int bid { get; set; }
        public Nullable<int> batch { get; set; }
        public Nullable<int> total { get; set; }
    }
}
