//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_and_Placement_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notice
    {
        public int nid { get; set; }
        public string uuid { get; set; }
        public Nullable<System.DateTime> notice_date { get; set; }
        public string description { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
    
        public virtual User User { get; set; }
    }
}
