//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_and_Placement_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostView
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public int pid { get; set; }
        public string uuid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public string title { get; set; }
    }
}
