//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_and_Placement_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int rid { get; set; }
        public string uuid { get; set; }
        public Nullable<int> sid { get; set; }
        public string active { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual User User { get; set; }
    }
}
