//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_and_Placement_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Registers = new HashSet<Register>();
        }
    
        public int sid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<double> package { get; set; }
        public Nullable<System.DateTime> visit_date { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<double> min_cpi { get; set; }
        public string backlog { get; set; }
        public Nullable<int> vacancy { get; set; }
        public string hrname { get; set; }
        public string description { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register> Registers { get; set; }
    }
}
