//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_and_Placement_Portal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int stid { get; set; }
        public string uuid { get; set; }
        public Nullable<int> cid { get; set; }
        public Nullable<double> package { get; set; }
        public Nullable<System.DateTime> palced_date { get; set; }
        public string placed { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
